### ISSUE TITLE
Can't compile?

### ISSUE THREAD

**Issue by fosskers** [alecmocatta/metatype#9]
I'm definitely on `nightly`, but for some reason I can't compile `metatype`. I'm told:
```
error[E0432]: unresolved import `std::raw`
  --> src/lib.rs:56:190
   |
56 | ...smute_copy}, ptr::{slice_from_raw_parts_mut, NonNull}, raw
   |                                                           ^^^ no `raw` in the root
```
Any idea what's going on here? 

Thank you :pray:

**Comment by MartinKavik** [comment]
Deprecated `raw` has been recently removed - https://github.com/rust-lang/rust/pull/86833.

To make it work with `raw`, you have to use a week old nightly Rust or older. You can add the file `rust-toolchain` to your repo with the content `nightly-2021-07-03`.

**Comment by alecmocatta** [comment]
Thanks for the report @fosskers and @MartinKavik, this is now fixed on v0.2.1. The new metadata API https://github.com/rust-lang/rust/issues/81513 makes much of this crate redundant so I'd recommend using that straight in new projects, but this fix should work in the interim.

**Comment by MartinKavik** [comment]
Thanks for the fast fix and recommendation! 
We are experimenting with [wasm-mt-pool](https://crates.io/crates/wasm-mt-pool) and [Seed](https://seed-rs.org/) (and then maybe [MoonZoon](http://moonzoon.rs/)) to bring multithreading to the browser world and if I'm not wrong, `metatype` is a transcendent dependency of `wasm-mt-pool` so we can't really move to a native Rust solution by ourselves.

**Comment by alecmocatta** [comment]
Got it. Yes the intermediate dependency is [`serde_traitobject`](https://github.com/alecmocatta/serde_traitobject) which is one of mine – it'll get updated eventually.

Seed and MoonZoom are cool btw, very excited about Rust in the browser! All the best with them!

**Comment by fosskers** [comment]
Thanks a lot guys!

**Comment by fosskers** [comment]
Yup, works like a charm.
